### ISSUE TITLE
Allow passing custom URI for the API base request

### ISSUE THREAD

**Issue by MarounMaroun** [slack-scala-client/slack-scala-client#67]
I'm referring to [this line](https://github.com/gilbertw1/slack-scala-client/blob/1efb3b1eb73494d4292bdaeb2bcbd9da2252ca98/src/main/scala/slack/api/SlackApiClient.scala#L27). This will allow easier testing instead of having to mock an HTTP server with port forwarding and host resolving.

Is this possible to do the separation? Or alternatively, is there a better way of mocking the Slack API?

**Comment by mccartney** [comment]
The thing I saw people doing in such cases was to increase visibility artificially. Mark it with `@VisibleForTesting` (or just a comment) and then you can mock with Mockito or similar in tests.

**Comment by lachatak** [comment]
Hello guys,
Really cool project!

I would like to write an end to end test for my bot. End to end test means I run my bot with real infrastructure elements in a dockerised environment with https://github.com/whisklabs/docker-it-scala.
End to end means nothing is mocked with Mockito or scalamock. Production classes are used, there is no altered or substituted classin this type of end to end test. The only thing might be different from real environment is the configuration. End to end test should be repeatable and should not depend on a real infrastructure element. Since the `SlackApiClient` does not allow me to provide a different url for slack - which might be mocked by [wiremock](http://wiremock.org/docs/getting-started/) or [mountebank](http://www.mbtest.org/) - it is not feasible to write a real end to end. 
I believe that there should be a way of creating `SlackApiClient` with provided slack url.
Even your own unit tests are running agains slack and uses configurable real slack channels which is I think not a correct unit test approach.
If you could provide your own url for mocked slack via wiremock or mountebank then it would be completely independent from the real slack which is more closer to a unit test.
What you think?

**Comment by mccartney** [comment]
Thanks for the feedback.

I am not sure what you are suggesting. Would you be so kind to clarify:
1. for our testing approach - should we have our own Slack server?
2. for the library itself - any particular suggestions on how to make the code more configurable? I am happy to review PRs.

**Comment by lachatak** [comment]
Hi. When you are planning to release the new version?

**Comment by mccartney** [comment]
> Hi. When you are planning to release the new version?

I can publish the new version this week. There's one more change I need.

**Comment by mccartney** [comment]
Version 0.2.5 has been published. Soon it should reach: https://mvnrepository.com/artifact/com.github.slack-scala-client/slack-scala-client

Can we close this issue?

**Comment by MarounMaroun** [comment]
Thanks for the update! Closing the issue.
